apiVersion: v1
kind: Service
metadata:
  name: scaletestapp-service
  labels:
    app: scaletestapp
spec:
  type: NodePort
  selector:
    app: scaletestapp
  ports:
    - name: http
      port: 80          # порт сервиса
      targetPort: 8080  # порт внутри контейнера (приложение слушает 8080)
